--POSTGRESQL

CREATE DATABASE MICASA;
\c MICASA;

CREATE TABLE PERSONAS(
    ID_PERSONA SERIAL PRIMARY KEY,
    PRIMER_NOMBRE VARCHAR(50) NOT NULL,
    SEGUNDO_NOMBRE VARCHAR(50),
    TERCER_NOMBRE VARCHAR(50),
    PRIMER_APELLIDO VARCHAR(50) NOT NULL,
    SEGUNDO_APELLIDO VARCHAR(50),
    FECHA_NACIMIENTO DATE NOT NULL,
    GENERO VARCHAR(1) NOT NULL CHECK (GENERO IN ('M', 'F')),
    BAUTIZADO BOOL NOT NULL DEFAULT FALSE,
    FECHA_BAUTIZO DATE,
    IDENTIFICACION VARCHAR(20) NOT NULL UNIQUE,
    TIPO_IDENTIFICACION VARCHAR(3) NOT NULL CHECK (TIPO_IDENTIFICACION IN ('CC', 'TI', 'CE', 'PAS', 'RC')),
    ESTADO_CIVIL VARCHAR(1) NOT NULL CHECK (ESTADO_CIVIL IN ('S', 'C', 'V', 'D', 'U')),
    CELULAR VARCHAR(20),
    EMAIL VARCHAR(100),
    DIRECCION TEXT,
    ESTADO BOOL NOT NULL DEFAULT TRUE,
    FECHA_CREACION TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    USUARIO_MODIFICACION INT,
    CONSTRAINT CHK_FECHA_BAUTIZO CHECK (FECHA_BAUTIZO IS NULL OR FECHA_BAUTIZO >= FECHA_NACIMIENTO)
);

CREATE INDEX IDX_PERSONAS_IDENTIFICACION ON PERSONAS(IDENTIFICACION);
CREATE INDEX IDX_PERSONAS_NOMBRES ON PERSONAS(PRIMER_NOMBRE, PRIMER_APELLIDO);

CREATE TABLE USUARIOS(
    ID_USUARIO SERIAL PRIMARY KEY,
    ID_PERSONA INT NOT NULL UNIQUE,
    USUARIO VARCHAR(50) NOT NULL UNIQUE,
    CLAVE VARCHAR(255) NOT NULL,
    ESTADO BOOL NOT NULL DEFAULT TRUE,
    ULTIMO_ACCESO TIMESTAMP,
    FECHA_CREACION TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    USUARIO_MODIFICACION INT,
    FOREIGN KEY(ID_PERSONA) REFERENCES PERSONAS(ID_PERSONA) ON DELETE CASCADE
);

CREATE INDEX IDX_USUARIOS_USUARIO ON USUARIOS(USUARIO);
CREATE INDEX IDX_USUARIOS_PERSONA ON USUARIOS(ID_PERSONA);

CREATE TABLE ROLES(
    ID_ROL SERIAL PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL UNIQUE,
    DESCRIPCION TEXT,
    ESTADO BOOL NOT NULL DEFAULT TRUE,
    FECHA_CREACION TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    USUARIO_MODIFICACION INT
);

CREATE TABLE USUARIOS_ROLES(
    ID_USUARIO_ROL SERIAL PRIMARY KEY,
    ID_USUARIO INT NOT NULL,
    ID_ROL INT NOT NULL,
    ESTADO BOOL NOT NULL DEFAULT TRUE,
    FECHA_CREACION TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    USUARIO_MODIFICACION INT,
    FOREIGN KEY(ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO) ON DELETE CASCADE,
    FOREIGN KEY(ID_ROL) REFERENCES ROLES(ID_ROL) ON DELETE RESTRICT,
    UNIQUE(ID_USUARIO, ID_ROL)
);

CREATE INDEX IDX_USUARIOS_ROLES_USUARIO ON USUARIOS_ROLES(ID_USUARIO);
CREATE INDEX IDX_USUARIOS_ROLES_ROL ON USUARIOS_ROLES(ID_ROL);

CREATE TABLE MINISTERIO(
    ID_MINISTERIO SERIAL PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL UNIQUE,
    DESCRIPCION TEXT,
    LIDER_ID INT,
    ESTADO BOOL NOT NULL DEFAULT TRUE,
    FECHA_CREACION TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    USUARIO_MODIFICACION INT,
    FOREIGN KEY(LIDER_ID) REFERENCES PERSONAS(ID_PERSONA) ON DELETE SET NULL
);

CREATE TABLE MINISTERIO_PERSONA(
    ID_MINISTERIO_PERSONA SERIAL PRIMARY KEY,
    ID_PERSONA INT NOT NULL,
    ID_MINISTERIO INT NOT NULL,
    CARGO VARCHAR(100),
    ESTADO BOOL NOT NULL DEFAULT TRUE,
    FECHA_INICIO DATE NOT NULL DEFAULT CURRENT_DATE,
    FECHA_FIN DATE,
    FECHA_CREACION TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    USUARIO_MODIFICACION INT,
    FOREIGN KEY(ID_PERSONA) REFERENCES PERSONAS(ID_PERSONA) ON DELETE CASCADE,
    FOREIGN KEY(ID_MINISTERIO) REFERENCES MINISTERIO(ID_MINISTERIO) ON DELETE CASCADE,
    UNIQUE(ID_PERSONA, ID_MINISTERIO, FECHA_INICIO),
    CONSTRAINT CHK_FECHA_FIN CHECK (FECHA_FIN IS NULL OR FECHA_FIN >= FECHA_INICIO)
);

CREATE INDEX IDX_MINISTERIO_PERSONA_PERSONA ON MINISTERIO_PERSONA(ID_PERSONA);
CREATE INDEX IDX_MINISTERIO_PERSONA_MINISTERIO ON MINISTERIO_PERSONA(ID_MINISTERIO);

CREATE TABLE FAMILIA(
    ID_FAMILIA SERIAL PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    DIRECCION TEXT,
    TELEFONO VARCHAR(20),
    ESTADO BOOL NOT NULL DEFAULT TRUE,
    FECHA_CREACION TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    USUARIO_MODIFICACION INT
);

CREATE TABLE FAMILIA_PERSONA(
    ID_FAMILIA_PERSONA SERIAL PRIMARY KEY,
    ID_PERSONA INT NOT NULL,
    ID_FAMILIA INT NOT NULL,
    PARENTESCO VARCHAR(50) NOT NULL CHECK (PARENTESCO IN ('PADRE', 'MADRE', 'HIJO', 'HIJA', 'ESPOSO', 'ESPOSA', 'ABUELO', 'ABUELA', 'NIETO', 'NIETA', 'OTRO')),
    ES_CABEZA_FAMILIA BOOL NOT NULL DEFAULT FALSE,
    FECHA_CREACION TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    USUARIO_MODIFICACION INT,
    FOREIGN KEY(ID_PERSONA) REFERENCES PERSONAS(ID_PERSONA) ON DELETE CASCADE,
    FOREIGN KEY(ID_FAMILIA) REFERENCES FAMILIA(ID_FAMILIA) ON DELETE CASCADE,
    UNIQUE(ID_PERSONA, ID_FAMILIA)
);

CREATE INDEX IDX_FAMILIA_PERSONA_PERSONA ON FAMILIA_PERSONA(ID_PERSONA);
CREATE INDEX IDX_FAMILIA_PERSONA_FAMILIA ON FAMILIA_PERSONA(ID_FAMILIA);


-- Tabla para registro de contactos adicionales
CREATE TABLE CONTACTOS(
    ID_CONTACTO SERIAL PRIMARY KEY,
    ID_PERSONA INT NOT NULL,
    TIPO_CONTACTO VARCHAR(20) NOT NULL CHECK (TIPO_CONTACTO IN ('TELEFONO', 'EMAIL', 'WHATSAPP', 'OTRO')),
    VALOR VARCHAR(100) NOT NULL,
    ES_PRINCIPAL BOOL NOT NULL DEFAULT FALSE,
    ESTADO BOOL NOT NULL DEFAULT TRUE,
    FECHA_CREACION TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    USUARIO_MODIFICACION INT,
    FOREIGN KEY(ID_PERSONA) REFERENCES PERSONAS(ID_PERSONA) ON DELETE CASCADE
);

CREATE INDEX IDX_CONTACTOS_PERSONA ON CONTACTOS(ID_PERSONA);

-- Tabla para permisos del sistema
CREATE TABLE PERMISOS(
    ID_PERMISO SERIAL PRIMARY KEY,
    NOMBRE VARCHAR(50) NOT NULL UNIQUE,
    DESCRIPCION TEXT,
    MODULO VARCHAR(50) NOT NULL,
    ESTADO BOOL NOT NULL DEFAULT TRUE,
    FECHA_CREACION TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    USUARIO_MODIFICACION INT
);

-- Tabla para asignar permisos a roles
CREATE TABLE ROLES_PERMISOS(
    ID_ROL_PERMISO SERIAL PRIMARY KEY,
    ID_ROL INT NOT NULL,
    ID_PERMISO INT NOT NULL,
    ESTADO BOOL NOT NULL DEFAULT TRUE,
    FECHA_CREACION TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    USUARIO_MODIFICACION INT,
    FOREIGN KEY(ID_ROL) REFERENCES ROLES(ID_ROL) ON DELETE CASCADE,
    FOREIGN KEY(ID_PERMISO) REFERENCES PERMISOS(ID_PERMISO) ON DELETE CASCADE,
    UNIQUE(ID_ROL, ID_PERMISO)
);

CREATE INDEX IDX_ROLES_PERMISOS_ROL ON ROLES_PERMISOS(ID_ROL);
CREATE INDEX IDX_ROLES_PERMISOS_PERMISO ON ROLES_PERMISOS(ID_PERMISO);

-- Tabla para auditoría de cambios
CREATE TABLE AUDITORIA(
    ID_AUDITORIA SERIAL PRIMARY KEY,
    TABLA VARCHAR(50) NOT NULL,
    ID_REGISTRO INT NOT NULL,
    ACCION VARCHAR(20) NOT NULL CHECK (ACCION IN ('INSERT', 'UPDATE', 'DELETE')),
    DATOS_ANTERIORES JSONB,
    DATOS_NUEVOS JSONB,
    ID_USUARIO INT,
    FECHA_ACCION TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(ID_USUARIO) REFERENCES USUARIOS(ID_USUARIO) ON DELETE SET NULL
);

CREATE INDEX IDX_AUDITORIA_TABLA ON AUDITORIA(TABLA);
CREATE INDEX IDX_AUDITORIA_USUARIO ON AUDITORIA(ID_USUARIO);
CREATE INDEX IDX_AUDITORIA_FECHA ON AUDITORIA(FECHA_ACCION);

-- Tabla para eventos de la iglesia
CREATE TABLE EVENTOS(
    ID_EVENTO SERIAL PRIMARY KEY,
    NOMBRE VARCHAR(100) NOT NULL,
    DESCRIPCION TEXT,
    TIPO_EVENTO VARCHAR(50) CHECK (TIPO_EVENTO IN ('CULTO', 'REUNION', 'CONFERENCIA', 'RETIRO', 'SERVICIO', 'OTRO')),
    FECHA_INICIO TIMESTAMP NOT NULL,
    FECHA_FIN TIMESTAMP,
    LUGAR VARCHAR(200),
    ID_MINISTERIO INT,
    ESTADO BOOL NOT NULL DEFAULT TRUE,
    FECHA_CREACION TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FECHA_MODIFICACION TIMESTAMP,
    USUARIO_MODIFICACION INT,
    FOREIGN KEY(ID_MINISTERIO) REFERENCES MINISTERIO(ID_MINISTERIO) ON DELETE SET NULL,
    CONSTRAINT CHK_FECHA_EVENTO CHECK (FECHA_FIN IS NULL OR FECHA_FIN >= FECHA_INICIO)
);

CREATE INDEX IDX_EVENTOS_FECHA ON EVENTOS(FECHA_INICIO);
CREATE INDEX IDX_EVENTOS_MINISTERIO ON EVENTOS(ID_MINISTERIO);

-- Tabla para asistencia a eventos
CREATE TABLE ASISTENCIA_EVENTOS(
    ID_ASISTENCIA SERIAL PRIMARY KEY,
    ID_EVENTO INT NOT NULL,
    ID_PERSONA INT NOT NULL,
    ASISTIO BOOL NOT NULL DEFAULT FALSE,
    OBSERVACIONES TEXT,
    FECHA_REGISTRO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(ID_EVENTO) REFERENCES EVENTOS(ID_EVENTO) ON DELETE CASCADE,
    FOREIGN KEY(ID_PERSONA) REFERENCES PERSONAS(ID_PERSONA) ON DELETE CASCADE,
    UNIQUE(ID_EVENTO, ID_PERSONA)
);

CREATE INDEX IDX_ASISTENCIA_EVENTO ON ASISTENCIA_EVENTOS(ID_EVENTO);
CREATE INDEX IDX_ASISTENCIA_PERSONA ON ASISTENCIA_EVENTOS(ID_PERSONA);

-- Comentarios en las tablas principales
COMMENT ON TABLE PERSONAS IS 'Almacena información personal de todos los miembros de la iglesia';
COMMENT ON TABLE USUARIOS IS 'Usuarios con acceso al sistema';
COMMENT ON TABLE ROLES IS 'Roles de seguridad del sistema';
COMMENT ON TABLE MINISTERIO IS 'Ministerios de la iglesia';
COMMENT ON TABLE FAMILIA IS 'Grupos familiares';
COMMENT ON TABLE EVENTOS IS 'Eventos y actividades de la iglesia';

-- Comentarios en columnas importantes
COMMENT ON COLUMN PERSONAS.TIPO_IDENTIFICACION IS 'CC=Cédula, TI=Tarjeta Identidad, CE=Cédula Extranjería, PAS=Pasaporte, RC=Registro Civil';
COMMENT ON COLUMN PERSONAS.ESTADO_CIVIL IS 'S=Soltero, C=Casado, V=Viudo, D=Divorciado, U=Unión Libre';
COMMENT ON COLUMN PERSONAS.GENERO IS 'M=Masculino, F=Femenino';
COMMENT ON COLUMN USUARIOS.CLAVE IS 'Almacenar hash bcrypt o similar, nunca texto plano';
